name: Doorstep
description: A new Flutter application.

version: 5.0.0+20


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  lottie: ^0.6.0
  flutter_open_whatsapp: ^0.1.2
  in_app_review: ^1.0.4
  stepper_counter_swipe: ^0.0.6
  carousel_slider: ^2.2.1
  url_launcher: ^5.6.0
  progress_dialog: ^1.1.0+1
  flutter_spinkit: "^4.1.2"

  bubble_bottom_bar: ^1.2.0
  flutter_staggered_animations: "^0.1.2"
  flutter_staggered_grid_view: ^0.3.4

  simple_animations: ^1.3.3

  image_picker: ^0.6.6+5


  glutton: ^1.0.5

  location: ^3.0.0
  geolocator:
  flutter_swiper: ^1.1.6
  badges: ^1.1.1
  flutter_cupertino_date_picker: ^1.0.26
  rating_bar: ^0.2.0
  intl:
  permission_handler: ^5.0.0+hotfix.5
  google_maps_flutter:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  json_serializable: ^3.3.0
  google_map_location_picker:

  flutter_cache_manager: ^1.1.3
#  package_info: ^0.4.0+13
  launch_review: ^1.0.1
  cache_image: "^1.0.5"
  shared_preferences: ^0.5.6+1
#  http: ^0.12.0+2
  get_it: ^4.0.2


#  google_maps_flutter: ^2.0.1
#  geolocator: ^6.1.14
  android_intent:
  provider:
  http: 
  stack_trace:
  package_info:

  cloud_firestore:
  firestore_ui:
  firebase_messaging:
  firebase_storage:
  firebase_database:
  firebase_core:
  firebase_auth:

#  cloud_firestore: ^0.13.6
#  firestore_ui: ^1.10.0
#  firebase_messaging: ^5.0.2
#  firebase_storage: ^3.0.3
#  firebase_database: ^3.1.6
#  firebase_core: ^0.4.0+8
#  firebase_auth: ^0.16.1

pubspec:
  yaml:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/dslogo.png
    - assets/icons/whatsapp.png
    - assets/imgs/tag.png
    - assets/location.json
    - assets/done.json
    - assets/coupon.json
    - assets/update.json
    - assets/no_shops.json
    - assets/empty_cart.json
    - assets/logo.json
    - assets/prescription.json


