name: Doorstep
description: A new Flutter application.

version: 3.1.6+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  lottie: ^0.6.0
  flutter_open_whatsapp: ^0.1.2
  google_sign_in: ^4.4.4
  rate_my_app: ^0.6.1+6
  stepper_counter_swipe: ^0.0.6
  firestore_ui: ^1.10.0
  carousel_slider: ^2.2.1
  url_launcher: ^5.6.0
  progress_dialog: ^1.1.0+1
  country_list_pick: ^1.0.0+4
  flutter_spinkit: "^4.1.2"
  simple_animations: ^1.3.3

  email_validator: '^1.0.0'
  image_picker: ^0.6.3+1
  location: ^3.0.0
  geolocator: ^5.3.1
  flutter_swiper: ^1.1.6
  badges: ^1.1.1
  flutter_cupertino_date_picker: ^1.0.26
  rating_bar: ^0.2.0
  intl: ^0.16.1
  flutter_polyline_points: ^0.1.0
  permission_handler: ^5.0.0+hotfix.5
  google_maps_flutter:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  json_serializable: ^3.3.0
  cloud_firestore: ^0.13.6
  google_map_location_picker: ^3.3.2

  flutter_cache_manager: ^1.1.3
  package_info: ^0.4.0+13
  launch_review: ^1.0.1
  cache_image: "^1.0.5"
  shared_preferences: ^0.5.6+1
  http: ^0.12.0+2
  get_it: ^4.0.2

  firebase_messaging: ^5.0.2
  firebase_storage: ^3.0.3
  firebase_database: ^3.1.6
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bgs/bg-gradient.png
    - assets/bgs/bg-signup.png
    - assets/fonts/AcuminProBold.otf
    - assets/fonts/AcuminProRegular.otf
    - assets/fonts/SfProTextRegular.ttf
    - assets/fonts/SfProTextSemibold.ttf
    - assets/gif/load.gif
    - assets/icons/facebook.png
    - assets/icons/google-plus.png
    - assets/icons/lock-grey.png
    - assets/icons/lock.png
    - assets/icons/logo.png
    - assets/icons/whatsapp.png
    - assets/icons/not-show.png
    - assets/icons/show-grey.png
    - assets/icons/show.png
    - assets/icons/twitter.png
    - assets/icons/user-grey.png
    - assets/icons/user.png
    - assets/imgs/centerLogo.png
    - assets/imgs/curve.png
    - assets/imgs/img.png
    - assets/imgs/dairy.jpg
    - assets/imgs/naan.jpg
    - assets/imgs/super_market.jpg
    - assets/imgs/grocery_store.jpg
    - assets/imgs/bbq.jpg
    - assets/imgs/tag.png
    - assets/location.json
    - assets/done.json
    - assets/coupon.json
    - assets/update.json
    - assets/logo.json
    - assets/imgs/bk.jpg


